INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(901,'Stv','Amare','Belay');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(902,'ber','Berhane','Kahsay');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(903,'ts','Tsegay','Kidane');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(904,'am','Amanuel','Yohannes');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(905,'em','Amanuel','Weldegerima');
----------------------------------------------------------------------------------------------

------ TO DEMONSTRATE PROJECTION EXAMPLES -----
INSERT INTO DEPARTMENT(ID,DEPT_NAME,LOCATION)VALUES(111,'HR','GA');
INSERT INTO DEPARTMENT(ID,DEPT_NAME,LOCATION)VALUES(112,'FINANCE','TX');
INSERT INTO DEPARTMENT(ID,DEPT_NAME,LOCATION)VALUES(113,'PROCUREMENT','GA');
INSERT INTO DEPARTMENT(ID,DEPT_NAME,LOCATION)VALUES(114,'IT','TX');

INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENT_ID)VALUES(20015,'AMANUEL',8000,114);
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENT_ID)VALUES(20016,'HELEN',5000,114);
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENT_ID)VALUES(20017,'BERIHAN',6000,113);