INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(901,'Stv','Amare','Belay');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(902,'ber','Berhane','Kahsay');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(903,'ts','Tsegay','Kidane');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(904,'am','Amanuel','Yohannes');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(905,'em','Amanuel','Weldegerima');