INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(901,'Stv','Steven','Doe');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(902,'ber','Berhane','Kahsay');
INSERT INTO USER(INT_CODE,STR_CODE,FIRST_NAME,LAST_NAME) VALUES(903,'ts','Tsegay','Kidane');